---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---

Minst et eksempel på bruk av følgende: *italic* **bold** ***italicbold***

# Reproduserbarhet

I 20xx (finn ut) oppstod det en replikasjonskrise. Denne startet innenfor psykologien, og ble for alvor offentlig kjent i 2015 da 270 forskere samarbeidet om å forsøke å replikere 100 studier som alle var publisert i ledende tidsskrifter innenfor fagfeltet. De klarte kun å få samme resultat i under halvparten av studiene, og dette var selv med hjelp fra forskerne som stod bak disse studiene (<https://psykologtidsskriftet.no/fagessay/2017/07/replikasjonskrisen>). Det har senere vist seg at disse replikasjonsproblemene finnes innenfor flere fagfelt, og i ettertid har det blitt større fokus på reproduserbarhet innenfor forskning. Reproduserbarhet er en forutsetning for replikerbarhet, så denne oppgaven skal vi ta for oss reproduserbarhet og hvorvidt bruk av R og R notebooks kan være en mulig løsning for å gjøre forskning reproduserbar, og dermed mer pålitelig.

## Litteraturgjennomgang

Replikerbarhet/reproduserbarhet Det er enda ingen allmenn definisjon av "reproduserbarhet" og "replikerbarhet". Noen bruker disse begrepene om hverandre (Bollen et al., 2015), og andre er nøye med å skille dem fra hverandre (Leek and Peng, 2015: Goodman et al., 2016). I denne oppgaven vil vi skille begrepene tydelig fra hverandre og bruke Bollens (et al., 2015) definisjoner av begrepene: "reproduserbarhet" oppstår dersom forskere klarer å komme frem til samme resultat ved å bruke samme prosedyre og samme datasett som gjort ved det opprinnelige studiet. "Replikerbarhet" oppstår dersom forskere klarer å komme frem til samme resultatet ved å bruke samme prosedyre og et nytt datasett. Hovedforskjellen er altså at ved "replikerbarhet" så skal det hentes inn nye data, men resultatet skal likevel bli det samme. De som prøver å replikere eller reprodusere studiet må altså ha tilgang til alt av data, kildekode og prosedyredetaljer. Man kan dermed si at reproduserbarhet er et krav for å kunne oppnå replikerbarhet.

### Problemets omfang

I lys av replikasjonskrisen og det økte fokuset på replikasjon, har flere tidsskrifter begynt å publisere tilhørende datasett sammen med artiklene. ferdig av Daniel

 ### Vil dagens løsning med arkiv av data og eventuell programkode hos tidsskriftene kunne løse problemet?

Det er flere forskere o.l. som ikke ønsker å gi fra seg informasjon, dette gjelder data de besitter, koder, fremgangsmåte, dokumentasjon, resultat, feil, problemer de har møtt på, hypoteser osv. Dette gjør det svært vanskelig å reprodusere en tidligere studie, på et senere tidspunkt. Siden det samlet er flere problem, vil det naturligvis også være flere løsninger som må tas i bruk for at full reproduksjon skal være oppnåelig og man skal komme frem til lignende konklusjoner med ny data og ny sammensetning.

Vi kan definere og skille mellom tekniske og menneskelige løsninger. Det menneskelige aspektet i problemstillingen er ofte knyttet til det forskerne selv velger å dele av data, informasjon, koder, hypoteser, fremgangsmåte, programvare og så videre. Det har ikke vært praktisert, og standard retningslinjer for hva som bør ansees som god forskningsskikk og praksis er nødt å komme på plass for å møte kravene om tilfredsstillende reproduksjon og replikasjon.
Det tekniske aspektet byr på mangel av data, koder, feil i programvare og feil som har oppstått underveis. Ved at man kan integrere og implementere programkode hos tidsskriftene, synlig eller usynlig, så skal det være mulig for andre forskere å reprodusere studien og gjøre den replikerbar. 

#### Oversikt over hva som bør sendes til tidsskriftene:
* En kode til å  kune lese inn dataen med
* En kode til å kalkulere og analysere dataen
* En kode for å teste i henhold til hypoetese
* En kode for å generere en rapport av resultatet

### Mulig løsning (teoretisk plan) “Compendium”, “Dynamic document”, “code chuncks” og “text chunck”

I henhold til Gentleman og Lang (2007) er det nøye å integrere koder og beregninger som blir brukt i dataanalyser, metodebeskrivelser og simuleringer. Dette kan enkelt gjøres via et kompendium, hevdet av Gentleman og Lang (2007). Kompendium er en kortfattet oversikt over hovedinnholdet i f.eks. en studie gitt i dette tilfellet. Kompendiumet til da gi en oversikt over innholdet, slik som tekst, kode, data, metodikk, hypotese, problemstilling og så videre. Dette gjør at kompendiumet enkelt kan distribueres i ulike kanaler, enkelt kan håndteres og oppdateres i henhold.

### Vil dagens løsning med arkiv av data og eventuell programkode hos tidsskriftene kunne løse problemet?


Compendium:

Dynamic document: <https://www.igi-global.com/dictionary/dynamic-reconstruction-concept-maps/8490> Et dokument som er ikke-permanent. Det er ikke ment å brukes til arkivering, men for å formidle informasjon. Digitalt dokument, det genereres av automatisert programvare som samler informasjon fra en database og deretter settet den inn i en forhåndsinnstilt mal.

Code chuncks: <https://rmarkdown.rstudio.com/lesson-3.html> R notebook lar oss ha "code chunks" i teksten.

Text chunck: Tekstbolker i dokumentet (R Notebook/Markdown)

### Mulig løsning R Notebooks

Daniel skrevet

## Analyse

Løser R Notebooks problemet med reproduserbarhet? Helt eller bare delvis?

Eksempler på "Code chuncks" ("R Code Block") og "text chunck i R notebook.

Har forskerne incentiver til å være "reproduserbare", eller må de tvinges?

I følge Florian Markowetz (20xx) er det følgende fem egoistiske hovedgrunner til at forskerne selv burde ønske å publisere reproduserbar forskning:

1.  Man unngår katastrofer

    -   blabla

2.  Det er lettere å skrive artikler

    -   blabla

3.  Lettere for fagfeller å forstå tankegangen

    -   blabla

4.  Det muliggjør kontinuitet i arbeidet

    -   Det vil for eksempel ikke være noen krise dersom forskeren har glemt fremgangsmåten vedkommende brukte i forskningen sin i fjor. Det vil være muligheter for å kunne se hvordan man har tenkt og jobbet med studiet.

5.  Hjelper deg å opparbeide et godt rykte

    -   Andre vil se på en forsker som publiserer reproduserbarforskning som en troverdig og grundig forsker, og dersom det noen gang blir problemer med noe av arbeidet, vil det være enkelt å vise og forklare hvordan man har tenkt og jobbet.

Er økt reproduserbarhet noe som vil tvinge seg frem eller er dagens økte interesse bare et blaff? Kan reproduserbarhet ha relevans i sektorer utenfor akademia?

## Konklusjon

## Litteraturliste

Sætrevik, B. (2017). Replikasjonskrisen. *Psykologtidsskriftet.* <https://psykologtidsskriftet.no/fagessay/2017/07/replikasjonskrisen>

Schmidt, M. L. 2015. Reproducible Research Using RMarkdown and Git through Rstudio. *RPubs by Rstudio.* <https://rpubs.com/marschmi/105639>
